version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongdb


  nodejs:
    build: .
    environment:
      - NODE_PATH=/usr/local/lib/node_modules
      - NODE_ENV=production
      - CONTAINER_IP=172.18.0.3
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    container_name: nodejs
